language: python
jobs:
  include:
  - name: Python 3.8.0 on Xenial Linux # Default OS if not specified
    python: 3.8 # this works for Linux but is ignored on macOS or Windows
before_install:
- pip3 install --upgrade pip
env:
install:
- pip3 install -r requirements.txt # all three OSes agree about 'pip3'3
script: pytest
