version: "3.8"
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    image: webhook:latest
    container_name: webhook
    environment:
      WOLFRAM_API_KEY: "$WOLFRAM_API_KEY"
      MAP_API_KEY: "$MAP_API_KEY"
      PROJECT_ID: "grocery-chat-bot-v1"
      POSTGRES_USER: sysadmin
      POSTGRES_PASSWORD: sysadmin030422
      POSTGRES_HOSTNAME: database
      POSTGRES_DB: storedb
      AUTH_USER: "$AUTH_USER"
      AUTH_PASSWORD: "$AUTH_PASSWORD"
    ports:
      - 8080:80
    expose:
      - 80
    volumes:
      - ./:/app
    networks:
      grocery_store_network:
        aliases:
          - webhook
  postgres: # Database (PostgreSQL)
    image: postgres:14
    container_name: postgres_database
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: sysadmin
      POSTGRES_PASSWORD: 'sysadmin030422'
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./data/samples:/docker-entrypoint-initdb.d/samples
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      grocery_store_network:
        aliases:
          - database

volumes:
  postgres-db:

networks:
  grocery_store_network:
    driver: bridge
    name: grocery_store_network