version: "3.8"
services:
  postgres: # Database (PostgreSQL)
    image: postgres:14
    container_name: postgres_database
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: sysadmin
      POSTGRES_PASSWORD: 'sysadmin030422'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      grocery_store_network:
        aliases:
          - database

volumes:
  postgres-db:

networks:
  grocery_store_network:
    driver: bridge
    name: grocery_store_network